<% if from %>FROM <%= from %><% end %>
<% if maintainer %>MAINTAINER <%= maintainer %><% end %>

<% if environment %>ENV <% environment.each do |name, value| %><%= name.upcase %>="<%= value %>" <% end %><% end %>

COPY <%= puppetfile %> /Puppetfile

<% if module_path && !master %>
COPY <%= module_path %> /etc/puppetlabs/code/modules/
<% end %>

<% if manifest && !master %>
COPY <%= File.dirname(manifest) %> /<%= File.dirname(manifest) %>
<% end %>

<% if use_hiera && !master %>
COPY <%= hiera_config %> /hiera.yaml
COPY <%= hiera_data %> /hieradata
<% end %>

RUN <% if apt_proxy %>echo "Acquire::HTTP::Proxy \"$APT_PROXY\";" >> /etc/apt/apt.conf.d/01proxy && echo 'Acquire::HTTPS::Proxy "false";' >> /etc/apt/apt.conf.d/01proxy && <% end %>apt-get -qq update && \
    apt-get -qqy install --no-install-recommends lsb-release wget ca-certificates && \
    wget <%= package_address %> && \
    dpkg -i <%= package_name %> && \
    rm <%= package_name %> && \
    apt-get update && \
    apt-get install -qqy --no-install-recommends puppet-agent="$PUPPET_AGENT_VERSION"-1"$CODENAME" && \
    apt-get remove --purge -y wget && \
    apt-get autoremove -y && \
    apt-get clean && \
    mkdir -p /etc/puppetlabs/facter/facts.d/ && \
    rm -rf /var/lib/apt/lists/* <% if apt_proxy %>&& rm -f /etc/apt/apt.conf.d/01proxy<% end %> && \


    <% if apt_proxy %>echo "Acquire::HTTP::Proxy \"$APT_PROXY\";" >> /etc/apt/apt.conf.d/01proxy && echo 'Acquire::HTTPS::Proxy "false";' >> /etc/apt/apt.conf.d/01proxy && <% end %>apt-get update && \
    apt-get install --no-install-recommends -y git-core && \
    <%= gem_path %> install r10k:"$R10K_VERSION" --no-ri --no-rdoc && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* <% if apt_proxy %>&& rm -f /etc/apt/apt.conf.d/01proxy<% end %> && \

    <%= r10k_path %> puppetfile install --moduledir /etc/puppetlabs/code/modules && \

    <% if apt_proxy %>echo "Acquire::HTTP::Proxy \"$APT_PROXY\";" >> /etc/apt/apt.conf.d/01proxy && echo 'Acquire::HTTPS::Proxy "false";' >> /etc/apt/apt.conf.d/01proxy && <% end %>apt-get -qq update && \
    FACTER_hostname=<%= hostname %> <%= puppet_path %> apply <%= manifest %> --detailed-exitcodes --verbose <% if puppet_debug %>--debug <% end %><% if show_diff %>--show_diff <% end %>--summarize <% if use_hiera %>--hiera_config=/hiera.yaml<% end %>; \
    rc=$?; if [ $rc -ne 0 ] && [ $rc -ne 2 ]; then exit 1; fi && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* <% if apt_proxy %>&& rm -f /etc/apt/apt.conf.d/01proxy<% end %> && \

    apt-get remove --purge -qqy puppet-agent git-core && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -fR /opt/puppetlabs/ && \
    rm -fR /etc/puppetlabs/ && \
    rm -rf /var/lib/apt/lists/*

<% if expose && !expose.empty? %>EXPOSE <%= expose.join(' ') %><% end %>
<% if volume && !volume.empty? %>VOLUME <%= volume.join(' ') %><% end %>

<% if entrypoint && !entrypoint.empty? %>ENTRYPOINT <%= entrypoint.to_s %><% end %>
<% if cmd && !cmd.empty? %>CMD <%= cmd.to_s %><% end %>

<% if image_user && !image_user.empty? %>USER <%= image_user.to_s %><% end %>
