name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '6'
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t ghcr.io/luckyraul/puppet-builder:${{ matrix.version }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        run: docker push ghcr.io/luckyraul/puppet-builder:${{ matrix.version }}
